### ISSUE TITLE
Missing parameters pop-up window for depth

### ISSUE THREAD

**Issue by Sepidak** [RichardFav/AnalysisGUI#10]
not sure why this shows up and why probe depth is set to 1060 um. Should I change this to the maximum depth? i.e 2910 in this example?
![Screenshot_2020-05-13_18-28-35](https://user-images.githubusercontent.com/28627358/81844878-ab74da00-9547-11ea-8668-c93ea68719fa.png)

**Comment by RichardFav** [comment]
These values are suggested values that are stripped out from the config files, so they may not necessarily represent the actual depths (it is assumed that you have this value somewhere in your notes). Therefore, you can change these values to what they should actually be. 

Note that you can also modify the depth values using the menu item "Data => Alter Parameter Values" in case you make a mistake (or want to use an alternative value).

**Comment by Sepidak** [comment]
I meant to ask is this not the total depth? In which case it should take the largest value In the config file. Just want to make sure that I enter this correctly. The screenshot of the corresponding config file is also n the attached image above.
________________________________

**Comment by Sepidak** [comment]
I will wait to confirm the question above before closing this:
Is this the full depth of the recording, basically depth at the tip?
