### ISSUE TITLE
are HD-modulated and HD cells combined in the venn diagram?

### ISSUE THREAD

**Issue by Sepidak** [RichardFav/AnalysisGUI#14]
function name: Freely Moving Cell Types
Please make sure that the HDMod circle in the venn diagram includes both HD cells and HD-modulated cells.

**Comment by RichardFav** [comment]
Currently only HD-modulated cells are included in the venn diagram. A patch will be applied so that both cell types will be included in the venn diagram.

**Comment by RichardFav** [comment]
The HD+HDMod grouping has been implemented within the Venn Diagram. The table/bar graph has been expanded to include both HD and HDMod cells. As a result, the HDMod/HD summary table at the top right is redundant and has been removed.
