### ISSUE TITLE
can't find the free-fixed correlation analysis function!!!

### ISSUE THREAD

**Issue by Sepidak** [RichardFav/AnalysisGUI#15]
I can't remember what this function was called because I can't find it anymore.
This was one of the latest functions you wrote, and we spent a long time discussing and testing it. This is the most important part for the freely moving data. It was used to find whether pairs of matched cells (fixed-free) had similar head velocity tuning by testing whether their head velocity tuning were correlated (PAGE 6 of our google doc). Either it has disappeared or somehow I can't locate it. 
I used MultiCompTest_2Exp.mcomp

**Comment by RichardFav** [comment]
The functions you are looking for (with regards to the freely moving analysis) are as follows:

Analysis Type - "**Freely Moving Cell Types**"
- **_Freely Moving Cell Type Statistics_**

Analysis Type - "**Angular Head Velocity Analysis**"
- **_Correlation Distributions (Freely Moving)_**
- **_Correlation Scatterplot (Freely Moving)_**
- **_Correlation Significance (Freely Moving)_**

All of these functions are accessible from the data file "**MultiCompTest_2Exp.mcomp**"

**Comment by RichardFav** [comment]
This is located in the "**Cluster Matching**" Analysis Type under the function "**Fixed/Freely Moving Spiking Frequency Correlation**".

**Comment by Sepidak** [comment]
Please move this under the freely moving analysis function
