### ISSUE TITLE
eye movemnet correlation (whole experiment) under eye tracking analysis crashes

### ISSUE THREAD

**Issue by Sepidak** [RichardFav/AnalysisGUI#20]
can't run this function any more

**Comment by Sepidak** [comment]
note that you were working on an older and incorrect mdata file. Maybe this was the reason why your results on eye movement correlation were different? I have deleted all the wrong mdata files in Z3. For this you need to use eye-tracking-corrected-data.mdata

**Comment by RichardFav** [comment]
This error was caused by an indexing error. This has been fixed and the update implemented on Subiculum.
