### ISSUE TITLE
"Fixed/Freely Moving Spiking Frequency Correlation" function freezes

### ISSUE THREAD

**Issue by Sepidak** [RichardFav/AnalysisGUI#21]
This happens when toggling between "Free Experiments" drop down menu.
Example .mcomp file = CA326_C_day3-CA407_1_day2

**Comment by Sepidak** [comment]
This function also freezes when just running it. The whole gui freezes

**Comment by RichardFav** [comment]
Both of these issues have been resolved and updated on Subiculum. Note that you may need to recreate the .mcomp files as older files may cause errors (**Note also that I have recreated "_CA326_C_dya3-CA407_1_day2.mcomp_" and is the file I have been using to test the Spiking Frequency Correlation functions)**.
