### ISSUE TITLE
option to extract and plot the AHV and fixed-significant (head velociy) overlap

### ISSUE THREAD

**Issue by Sepidak** [RichardFav/AnalysisGUI#28]
This should be done on matched cells which are both in the openfield and the fixed datasets.
currently we don't know how many of the fixed-significant cells (any) are in the matched dataset used for the cell types analysis. By finding this we can extract the above and make a venn diagram.
![Screenshot_2020-05-20_23-20-19](https://user-images.githubusercontent.com/28627358/82503083-8573aa80-9af0-11ea-8f1b-fe1840ad6883.png)

**Comment by RichardFav** [comment]
A new function called "Correlation Significance Overlap" has been added to the "Angular Head Velocity Analysis" function group and has been updated on Subiculum (if not present, then you will need to pull the latest update).

**Comment by Sepidak** [comment]
There seems to be a bug. This function crashed on subiculum at the plotting step. 
Testing on multiple experiments. Unfortunately can't save this as .mcomp as it also crashes on loading so will have to eave it open on subiculum.

**Comment by RichardFav** [comment]
The General Exclusion filter has not been applied to this function. I will fix this up and apply an update.

**Comment by RichardFav** [comment]
The general exclusion filter is now working and has been updated on Subiculum.

**Comment by Sepidak** [comment]
test experiment: 6-Expt-Filt-Calc.mcomp
somehow the overlap number in the diagram, which consistently comes at 32-33 at multiple rounds of 1000 iterations, is always 2-3 more than what we get from the "Correlation Sigificance (Fixed)" function when AHV is chosen as a filter parameter. There the significant cells are consistently 29-30. Any idea what this could be?

**Comment by RichardFav** [comment]
This due to the free cell types not being filtered correctly. A fix for this has been applied and an update placed on Subiculum.
