### ISSUE TITLE
one of the .opend dataframes won't load

### ISSUE THREAD

**Issue by Sepidak** [RichardFav/AnalysisGUI#29]
Can't figure out what the issue with the file is. It's here:
/home/skeshav/code/Analysis/data_files/2_Input_Files/Z5 - Freely Moving Spike Freq Files/0-to-900-sec-Shuffle/CA326_C_day1.opend

**Comment by RichardFav** [comment]
This was due to the naming of the fixed/free matching file names. Make sure the names are consistent between Adam's datafile name (the .opend file) and the .cdata files that comprise the .ccomp file.
