### ISSUE TITLE
non-matching table and graphs in "Fixed/Free Spiking Correlation Histogram" under "freely moving analysis"

### ISSUE THREAD

**Issue by Sepidak** [RichardFav/AnalysisGUI#30]
tables show lower values fro significant cells than what is in the graph.
test Experiment: I leave this open on Subiculum is at it large

**Comment by RichardFav** [comment]
The table and bar is confusing. I will add 2 more lines to the table displaying the Mean and SEM values.

**Comment by RichardFav** [comment]
The issue has been addressed in Issue #31. The table has also been expanded to display the mean and SEM values 

As aside, from analysis of the data it appears that there are 2 files with 70+ cells whereas there are 3 files with 14-16 cells. This is causing the skewing in the mean statistics over all experiments relative to the total count percentages.
