### ISSUE TITLE
"Fixed/Free Spiking Correlation Histogram" doesn't show the correct number of cells

### ISSUE THREAD

**Issue by Sepidak** [RichardFav/AnalysisGUI#31]
test experiment: multiple experimentS open on Subiculum
issue: total number of matched AHV cells is 43 based on the "freely moving cell type statistics" function. But in fixed/free spiking correlation (histogram), when AHV cells are picked in the filter, the total is 19. This must be a bug as these two numbers should be the same (43).
This issue may be also related to #30

**Comment by RichardFav** [comment]
This appears that the General Exclusion filter is still not working correctly. I will work on fixing this up.

**Comment by RichardFav** [comment]
After much effort I have finally managed to sort out the issue. The numbers now match between the "Fixed/Free Spiking Correlation (Histogram)" and "Freely Moving Cell Type Statistics" functions. Note that the code has also been update for the Scatterplot function (which shares a large chuck of code with the histogram function).

**Comment by Sepidak** [comment]
This seems to be fixed. The only confusing thing is that now, at least in the histograms, significant anti-correlated cells are also highlighted. However, I think that in the table still only the correlated (positive pcc) are considered as significant, which is what we want. Could you please confirm that this is the case?

**Comment by RichardFav** [comment]
I was going to ask if you wanted the negative correlated cells added as well. In any case, I have removed the negative correlated values from both the graph and tables (I have also done this for the scatterplot as well).

**Comment by Sepidak** [comment]
test experiment:  /home/skeshav/code/Analysis/data_files/2_Input_Files/Z4 - Multi Comparison Data Files/1Exp_CA326_C_day2_test.mcomp
This issue still doesn't seem to be solved. I just checked a very small experiment with 4 matched cells that are present in both fixed and open-field datasets. So the total number of cells shown in both "Freely Moving Cell Type Statistics" and "Fixed/Free Spiking Correlation Histogram" should be 4. But while it's correct for the former, for the latter it's 6. There is no filter involved in this experiment. Therefore, this cant be due to filtering. There seems to be another bug involved.

**Comment by Sepidak** [comment]
following the previous issue, I further tested this on another experiment (CA406_1_day1) . Seems like you are calculating the total number of "fixed cells"  for the "Fixed/Free Spiking Correlation Histogram" function. Please remember that for these analyses we are looking at the **"MATCHED" cells that also exist in the ".opend" data frames**. Total number of fixed cells is completely irrelevant here.

**Comment by RichardFav** [comment]
A new update addressing this issue has been put on Subiculum. It appears to work for the 6-experiment .mcond data file, but further testing is required before this issue is fully resolved.
