### ISSUE TITLE
discrepancy in total number of cells between "Freely Moving Analysis" and cells shown in the drop-down under "Fixed/Free Spiking Correlation (Individual Cell) 

### ISSUE THREAD

**Issue by Sepidak** [RichardFav/AnalysisGUI#32]
related to issues #30  and  #31 

test experiment: multiple. open on subiculum
Please note in all examples, all regions except RSPd and RSPg are excluded.

Based on "Freely Moving Cell types Statistics" the total number of matched-cells which are in both datasets are 82, but in the drop-down I'm getting 85. These two should be the same.

**Comment by RichardFav** [comment]
This issue was in fact related to Issues #30 and #31 and has been resolved (update is available on Subiculum).
