### ISSUE TITLE
bug in "Phase Spiking Rate Comparison (Whole Exp)" under "Rotation Analysis"

### ISSUE THREAD

**Issue by Sepidak** [RichardFav/AnalysisGUI#33]
Test Experiment: /home/skeshav/code/Analysis/data_files/2_Input_Files/Z3 - Multi Experiment Data Files/ALL-fixed-cells-final-Filtered.mdata

"show DS cell proportion of MS cell Population" doesn't work.
This used to allow defining DS cells based on whether they are MS, or irrespective.

**Comment by Sepidak** [comment]
This is the same for UniformDrift Analysis--> UniformDrift Phase Spiking Rate Comparison (Whole Exp)

**Comment by RichardFav** [comment]
A fix has been added to address this issue and is now available on Subiculum.
