### ISSUE TITLE
"Rotation Filter Parameters" doesn't work with any of the ROC analysis functions

### ISSUE THREAD

**Issue by Sepidak** [RichardFav/AnalysisGUI#34]
test experiment: 
/home/skeshav/code/Analysis/data_files/2_Input_Files/Z3 - Multi Experiment Data Files/ALL-fixed-cells-final-Filtered.mdata

Can't filter by any of the fields (cluster signal type, region name, recording layer)
tried this with "Direction ROC Curves (Whole Exp)", "Direction ROC AUC Histograms", and "Motion/Direction Selectivity Cell Grouping Scatterplot"

**Comment by RichardFav** [comment]
The "**Direction ROC Curves (Whole Experiment)**" and "**Direction ROC AUC Histograms**" have been fixed up with the update now available on Subiculum. 

The "**Motion/Direction Selectivity Cell Grouping Scatterplot**" calculations now run to completion, however, there are several plotting options which cause the program to crash. As a result, this function is not yet considered to be complete.

**Comment by Sepidak** [comment]
could you please check that 
1-the scatter plot under "Motion/Direction Selectivity Cell Grouping Scatterplot" does not have an error? It's ok to test this without the grouping option.
2-the bar graphs under auROC Significance/Histogram is correct and also output the percentage +SEM (as in issue #36)

**Comment by RichardFav** [comment]
The Motion/Direction Selectivity Cell Grouping Scatterplot has been update with the features mentioned above (while making sure there are no errors). Note that the grouping options have not been implemented properly and will need to be addressed in a separate issue. In any case, this update has been placed onto Subiculum.
