### ISSUE TITLE
Option to extract (mean percentages+SEM) in multiple functions

### ISSUE THREAD

**Issue by Sepidak** [RichardFav/AnalysisGUI#36]
Tables only show the total number of cells, but Values in the graphs are not shown (mean percentage +- SEM). Add this for the following functions:
1- "Correlation Significance (Fixed)"  under "Angular Head Velocity Analysis"
2- "Correlation Significance (Freely Moving)"  under "Angular Head Velocity Analysis"
3- "Phase Spiking Rate Comparison (Whole Experiment)" under "Rotation Analysis"
4- "Freely Moving Cell Type Statistics" under "Freely Moving Analysis"
5- "UniformDrift Phase Spiking Rate Comparison (Whole Experiment) under "UniformDrift Analysis"

**Comment by RichardFav** [comment]
Include option to allow showing either total counts or mean + SEM in table.

**Comment by RichardFav** [comment]
This functionality has been added into the program for the functions listed above. The values in the summary table can be toggled between cell counts and mean +/- sem by selecting the "Show Cell Count" plotting parameter.
