### ISSUE TITLE
opion to add info about openfield dataframe to the experimnet information field

### ISSUE THREAD

**Issue by Sepidak** [RichardFav/AnalysisGUI#38]
Currently we don't have the option to find which free cell types are also present in .opend dataframe, whether matched or non-matched with a fixed cell. Can this be added somehow?

**Comment by RichardFav** [comment]
For Free experiments only, add all matching cells between the Free .cdata file and Adam's Datafile regardless of whether there is a match (i.e, put all matching cells between the .cdata file and Adam's data file).

**Comment by RichardFav** [comment]
This feature has now been added to the program and is available on Subiculum.
