### ISSUE TITLE
"Pooled Neuron LDA" under "Diretcion LDA" crashes  when choosing "pool All Experiments"

### ISSUE THREAD

**Issue by Sepidak** [RichardFav/AnalysisGUI#48]
test exp: /home/skeshav/code/Analysis/data_files/2_Input_Files/Z3 - Multi Experiment Data Files/ALL-fixed-cells-final-Filtered.mdata

LDA parameters: min cell count=12; min trial count=14; comparison conditions=black, uniform, motordrifting; solver=eigen; cell signal type=all cells

**Comment by RichardFav** [comment]
This may mean we have to temporarily output data files and recombine them afterwards. I'll look into this.

**Comment by RichardFav** [comment]
This error has been resolved with an update now available for Subiculum.

**Comment by RichardFav** [comment]
This issue was due to the normalisation step introducing NaN's into the spiking frequency array (due to dividing by a standard deviation of zero - this happens when all spiking frequencies are zero for a given trial). This has been fixed and updated on Subiculum.
