### ISSUE TITLE
"Speed LDA Comparison (pooled experiments)" gets exponentially slower during shuffling and seems to saturate or get stuck

### ISSUE THREAD

**Issue by Sepidak** [RichardFav/AnalysisGUI#49]
test experiment: /home/skeshav/code/Analysis/data_files/2_Input_Files/Z3 - Multi Experiment Data Files/ALL-fixed-cells-final-Filtered.mdata
LDA parameters: min cell count=12; min trial count=14; comparison conditions=black, uniform,  solver=eigen; cell signal type=all cells

This happens even with the smallest number of shuffles (5) when "pool all experiments" is selected. We used to be able to run both this and the "pooled neuron LDA function" (#48) with 500 shuffles and using the "pool all experiments" option. We need to do 1000 shuffles for each of these functions. Currently this is impossible (even with 5). 

Please note that we also need to be able to run this on 3 comparison conditions (not just the two above) which, similar to issue #48, will include black, uniform and motordrifting.

**Comment by RichardFav** [comment]
The issue responsible for this error has been found and resolved on Subiculum.
