### ISSUE TITLE
eye tracking: add option for individual cells

### ISSUE THREAD

**Issue by Sepidak** [RichardFav/AnalysisGUI#5]
Add individual cells plotting and correlation graph (including the pcc) from which the whole- experiment plots are mad

**Comment by RichardFav** [comment]
Here is a schematic of the graph:
![Individual Cell Eye-Tracking Graph Schematic](https://user-images.githubusercontent.com/23033580/81573449-194dc400-93d7-11ea-9543-d0e68cca3b52.png)

**Comment by RichardFav** [comment]
Graph is complete and running on Subiculum. Needs to be properly vetted by Sepi before closing this issue.

**Comment by Sepidak** [comment]
for single cells, can we please add the cluster (and channel ID) of each cell, similar to rotation analysis?

**Comment by RichardFav** [comment]
Cluster/Channel ID has been added to function and updated on Subiculum.
