### ISSUE TITLE
"All bins" under Velocity ROC Significance

### ISSUE THREAD

**Issue by Sepidak** [RichardFav/AnalysisGUI#53]
is this the average across all bins?

**Comment by RichardFav** [comment]
The "All Bins" selection is indeed the average across all velocity/speed bins.

Also, there was an error in the code whereby the other velocity bins were not being displayed correctly (this parameter is supposed to separate out the velocity response into bin sizes whose size is given by the calculation parameter "**Velocity Bin Size (deg/sec)**")
