### ISSUE TITLE
potential bug in correlation calculation or display of results in the eye tracking function

### ISSUE THREAD

**Issue by Sepidak** [RichardFav/AnalysisGUI#54]
Eye Movement Correlation(individual cell)
for many examples the sign and the magnitude of correlation seems off and cells that seem clearly modulated by eye movement are non-sig whereas those that are not are significant. 
experiment: eye-tracking-corrected-data.mdata.
note that the IDs below are with the usage of general filter which is set to exclude all regions except RSPd.
pre event signal frame count =2
post event signal frame count = 8
some examples:
CA515_B_day2, cell cluster index 39, cell ID 3811:  T-to-M has r of -0.0197, whereas the slope is positive. 
CA514_C_day2, cluster ID 1, cell ID 130,2 M-to-t has r of 0.5237, but here it seems like this should be negative.  
CA514_C_day2,  cluster ID 6, cell ID 696, T-to-M has r of 0, this doesn't match with the correlation line and the firing rate histogram of this cell.
CA514_C_day2, cluster ID 15, cell ID 1019, T-to-M has r of -0.552. Again this is a positive correlation so r should be positive and the firing of this cell seems to be strongly correlated with eye movement but it's not significant!

**Comment by RichardFav** [comment]
It appears the issue here was due to the general exclusion filter not being properly applied to the signal being shown (even though the correlation/p-values were correct). This has been fixed and update is available for the pull on Subiculum.
