### ISSUE TITLE
"Speed LDA Comparison (Individual Experiments)" crashes

### ISSUE THREAD

**Issue by Sepidak** [RichardFav/AnalysisGUI#55]
test exp: All-fixed-cells-final-Filtered.mdata
dependent speed range = 5 to 10
speed bin size = 5 deg/s
min cell count =20
min trials =14
conditions = unfirom/balck/motordrifting

**Comment by RichardFav** [comment]
This error was introduced by fixing up the "**Speed LDA Comparison (Whole Experiment)**". This issue has been resolved and an update placed on Subiculum.
