### ISSUE TITLE
comparing AHV pearson's r values between dark and light conditions (freely moving data)

### ISSUE THREAD

**Issue by Sepidak** [RichardFav/AnalysisGUI#56]
This is to see if there is a difference in strength of correlations for head velocity between dark and light (light1  or light2) conditions.
To do this we need the following steps. Bare in mind that we have paired data, meaning that for each cell we have the values both in dark and in light conditions. Therefore, the final statistical test should be a paired test.

1-extract the ahv_pearson_r_pos and ahv_pearson_r_neg from the freely moving data frames
2-get the absolute values of these r's 
3-plot all (**give option to choose all cells or AHV cells only**) as a "swarm/violin" plot or as a bar plot (mean+- SEM) for dark and light1 (or light2).
4-output the mean+-SEM values and the p value for a paired-t-test between dark and light1 or light2.

**Comment by RichardFav** [comment]
A new function called "AHV Correlation Comparison" has been added to the "Freely Moving Analysis" function group, and is now available on Subiculum.

The paired t-test that was used to calculate the p-values is the ttest_rel function from the scipy.stats module:

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_rel.html

**Comment by RichardFav** [comment]
As the data values are not normally distributed, the Wilcoxon non-parameteric test was used instead to calculate the p-values. This function can be found at the following link:

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.wilcoxon.html
