### ISSUE TITLE
update HD and HD modulated definitions

### ISSUE THREAD

**Issue by Sepidak** [RichardFav/AnalysisGUI#6]
**HD cells**
under both light 1 and light2 must have:
1-mean_vec_length >= 0.2
2-rayleight_tes_p < 0.001

**HD modulated cells**
under both light 1 and light2 must have:
1- 0.1 < mean_vec_length < 0.2
2-rayleight_tes_p < 0.001

**Comment by RichardFav** [comment]
Have added these new definitions to the project and will test on Subiculum.

**Comment by Sepidak** [comment]
ok thanks! are these hard-coded. If yes then it's best that you tell me where they are in the code incase I need to change the thresholds again.

**Comment by RichardFav** [comment]
Yes they are. They are located in "**main_analysis.py**" in the "**append_data**" function for the **FreelyMovingData** class (to find it just do a search for "_def append_data(self, data, f_data)_" in **main_analysis.py**). I've added comment to the parameters so you know what each does.

**Comment by Sepidak** [comment]
note I have change these two parameters:
 p_rayleight_hd is changed from 0.001 to 0.01
p_rayleight_hd_mod is changed from 0.001 to 0.01
