### ISSUE TITLE
Direction and Velocity ROC curves (Single Cell) are broken

### ISSUE THREAD

**Issue by Sepidak** [RichardFav/AnalysisGUI#60]
Test experiment: All-fixed-cells-final-Filtered
Condition: any but use black to ensure it exist
foR velocity ROC, velocity bin size : 5 deg/s 

These were working fine as of last week. But now they crash on plotting (velocity) or not showing the curves at all (Direction).

**Comment by RichardFav** [comment]
There was a change made in the code that caused this issue. A fix has been added to the code and is now updated on Subiculum.
