### ISSUE TITLE
heatmaps for direction selectivity and velocity 

### ISSUE THREAD

**Issue by Sepidak** [RichardFav/AnalysisGUI#61]
Create two sets of plotting related to the "spiking rate heatmap" function. One for direction and the other for velocity:

**Direction** 
Instead of sorting the cells based on depth, sort by the direction selectivity index or the direction auROC (give option to choose one or the other). For auROC we need the non-rectified values (range between 0-1). For direction selectivity index use (deltaCW-deltaCCW spiking frequency)/(deltaCW+deltaCCW spiking frequency). If (deltaCW+deltaCCW)=0,  return the sign of (deltaCW-deltaCCW).

**Velocity** 
Instead of sorting the cells based on depth, sort either the CW or the CCW directions based on the Pearson's r taken from the Angular Head Velocity Analysis -->individual cells (fixed).

**Comment by RichardFav** [comment]
Both heatmap types have been included into the program. 

1) Direction - A new plotting parameter "**Heatmap Sort Type**" has been added to this function, and can take value of either "**Probe Depth**" or "**Direction Selectivity Index**".

2) Velocity - A new function "**Spiking Rate Heatmap (Fixed)**" has been added to the "**Angular Head Velocity Analysis**" function types. The heatmap sorting is achieved by the plotting parameter "**Heatmap Sort Type**" (which is either "**Pearson Correlation (CW)**" or "**Pearson Correlation (CCW)**")

**Comment by Sepidak** [comment]
add AUC and will revise later for using velocity instead of time bins for the velocity heatmaps.

**Comment by RichardFav** [comment]
A new heatmap function called "**Direction ROC Spiking Rate Heatmap**" has been added to the "**ROC Analysis**" function types. Note that the heatmaps can be sorted by AUC ROC values for:

1) **CW vs BL**
2) **CCW vs BL**
3) **CCW vs CW**

**Comment by Sepidak** [comment]
the above functions work. However, one AHV cells are selected from the rotation filter parameters, the plotting returns none.
test experiment: ALL-FIX-FREE-FINAL-all-light1.mcomp

**Comment by RichardFav** [comment]
A fix has been put in place to address this issue with the new version now available on Subiculum.

**Comment by Sepidak** [comment]
This bug (selecting AHV cells) is still there for the angular head velocity heatmap

**Comment by RichardFav** [comment]
Bug has been fixed for Angular Head Velocity Heatmap. Will expand heatmaps so that they are binned by velocity rather than time.

**Comment by Sepidak** [comment]
implement option to sort multiple conditions based on one condition (i.e. sort motordrifting  based on black so that they both show the same order of cells)

**Comment by Sepidak** [comment]
After multiple rounds of testing with normalisation to the peak, baseline, or average, none seems to be giving a meaningful outcome. I think we should have done this differently, by first subtracting the baseline from all bins (so the first bin will be 0 for all cells), and then for each cell normalising to the maximum firing across "all the 3 conditions". When we normalised to the max, we did it within each condition and that must be the reason why the outcome was weird. We want to compare the 3 conditions so the normalisation (when using the peak) should be based on all the 3. Otherwise they will all go from 0 to 1 and look the same.

**Comment by Sepidak** [comment]
The above is implemented and working but it doesn't show a clear pattern to visualize cells that are responding to both conditions. Could we add an additional sorting option where we sort by the mean of sorting values across the two conditions?
