### ISSUE TITLE
Creation of Correlation Parameter Comparison/Fit Parameter functions for fixed experiments.

### ISSUE THREAD

**Issue by RichardFav** [RichardFav/AnalysisGUI#68]
These functions are to mirror that which has already been created for the freely moving experiments (namely the "**AHV Correlation Comparison**" and "**AHV Fit Parameters**" functions located in the "**Freely Moving Analysis**" function group).

**Comment by RichardFav** [comment]
These functions have been created and are now available within the program, and are named "**Correlation Comparison (Fixed)**" and "**Correlation Fit Parameters (Fixed)**" available under the "**Angular Head Velocity Analysis**" function group. 

Note that the two freely moving analysis functions named in the issue above have also been moved to the "**Angular Head Velocity Analysis**" function group and (for consistency purposes) are also renamed as:

- "**AHV Correlation Comparison**" => "**Correlation Comparison (Freely Moving)**"
- "**AHV Fit Parameters**" => "**Correlation Fit Parameters (Freely Moving)**"

These new functions are available on Git so a pull request will need to be made on Subiculum to apply these changes.

**Comment by Sepidak** [comment]
add an option to combine CW and CCW data points, so that they are all shown on the same plot and the stats will also be done on all together.

**Comment by RichardFav** [comment]
The option to combine metrics has been added to the function "**Correlation Comparison (Fixed)**", and is possible by using the plotting parameter "**Combine Metrics Between Phases**". This is now available on Subiculum.

**Comment by Sepidak** [comment]
Need to also implement a measure for residuals to use instead of/in addition to the Pearson's correlation. Either the standard error or the sum of squared residuals.

**Comment by RichardFav** [comment]
This has been implemented within the function "**Correlation Comparison (Fixed)**", and can be accessed via the "**Metric Type**" plotting parameter using the value "**Fit Error**".

Note that there are 3 different types of fit errors that can be calculated (accessed by setting the value of the calculation parameter "**Error Calculation Type**"):

1. Covariance - Value is calculated using the "**curve_fit**" function. Additionally, the fit function assumes 0 intercept value (i.e, y = mx only)
2. Sum-of-Squares - Value is calculated using the "polyfit" function (fit assumes that y = mx + c)
3. Standard Error - Value is calculated using the "linregress" function (fit also assumes that y = mx + c)
