### ISSUE TITLE
Whole experiment addition to eye movement correlation

### ISSUE THREAD

**Issue by Sepidak** [RichardFav/AnalysisGUI#7]
population firing rate histogram (average of all cells), and correlation plot.
i.e this will be similar to choosing an "analyse all experiments" box  under "rotation trial spiking rates" function.

**Comment by RichardFav** [comment]
This has been added to the function and is now available on Subiculum.

**Comment by Sepidak** [comment]
Thank you Richard! Seems this is done for individual experiments and not all experiments. Could you please check?

**Comment by RichardFav** [comment]
The original update only included analysis for a single experiment. In addition, this analysis did not take into account the general filter (for excluding cells from specific regions etc.).

I have updated the program to allow the user to analyse either a single cell, single experiment or all experiments. Furthermore, the general filter has also been included into this analysis function. Finally, for the individual cell analysis, the cell's channel region has been included in the figure's title (in addition with the cluster/channel ID#).

This update has been applied to Subiculum.

**Comment by RichardFav** [comment]
I added in some other changes to the program as there was a disparity from the results generated on my local machine vs that generated on Subiculum. This issue has been fixed up and now the program is running correctly.

**Comment by Sepidak** [comment]
What was this issue?
